############################################
##  .travis.yml para el uso del Servidor  ##
##  Basado en Ubuntu 14.04                ##
############################################

# Habilito uso de SU
sudo: required

# Habilito uso de Trusty beta (Ubuntu 14.04)
dist: trusty

# Selección del lenguaje: C++
language: cpp

# Seleeción de compilador gcc
compiler:
  - gcc

# Solo realizo build sobre los branches elegidos
branches:
  only:
    - master
    - develop

# Notifico a Slack los informes de Travis CI
notifications:
  slack: tallerdeprogramacion2:HL5boJMM5KdLnwsD0DFMMxNx

# Instalo todas las dependencias. (Teniendo en cuenta el uso de Trusty beta)
install:
  - cd server
  - chmod 777 server_install_v0.2.sh
  - sudo ./server_install_v0.2.sh -travis
  - cd ..  

# Inicio el script para correr las pruebas y enviar los datos de code coverage a coveralls.io, a partir de CMake.
script: 
  - cd server
  - mkdir build 
  - cd build
  - cmake -DCOVERALLS=ON -DCMAKE_BUILD_TYPE=Debug ..
  - make
  - make coveralls

